name: Push - all branches
on:
  push:

jobs:
  lint:
    name: Flake8 Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8 lint
        run: |
          flake8

  publish_image:
    name: Publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t squamsh/skydive
      - name: publish
        run: |
          docker login -u squamsh -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push squamsh/skydive
